Option Strict On
Option Explicit On
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports Microsoft.VisualBasic.ApplicationServices

Namespace My

    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the Application tab.
    '
    Partial Friend Class MyApplication

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
            Me.IsSingleInstance = False
            Me.EnableVisualStyles = True
            Me.SaveMySettingsOnExit = True
            Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
        End Sub

        <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = Global.SysContab.FrmLogin2008
        End Sub

        Private Sub MyApplication_Startup(sender As Object, e As StartupEventArgs) Handles Me.Startup
            'Comprobar Nueva Instancia del Servidor
            Dim NuevaInstancia As String =
                GetSetting(
                My.Application.Info.ProductName.ToString,
                "CxCadena",
                "NServer_RAMAC")
            '
            If NuevaInstancia.Trim.Length > 0 Then
                If NuevaInstancia.Trim =
                    "192.168.0.2" Then SaveSetting(
                    My.Application.Info.ProductName.ToString,
                    "CxCadena",
                    "NServer_RAMAC",
                    "")
            End If

            ''Verificar si hay datos de Configuracion
            Dim s As String() = LeeData()

            If s(0).Trim.Length = 0 Then    'Es la Primera vez que se corre el Sistema y no se ha configurado nada en el registro
                Me.MainForm =
                    Global.SysContab.FrmConfiguracionServer  ' Global.SysContab.frmConfigurar                           
            End If

        End Sub
    End Class
End Namespace
